<!-- BEGIN PAGE LEVEL STYLES -->
<link href="<?php echo base_url('../assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css');?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url('../assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css');?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url('../assets/global/plugins/bootstrap-modal/css/bootstrap-modal.css');?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url('../assets/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css');?>" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url('../assets/global/plugins/bootstrap-datepicker/css/datepicker3.css');?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo base_url('../assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css');?>"/>
<link href="<?php echo base_url('../assets/global/plugins/fancybox/source/jquery.fancybox.css');?>" rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL SCRIPTS -->